### ISSUE TITLE
Erroneous "Resolution too big" error

### ISSUE THREAD

**Issue by malexj93** [rlaPHOENiX/DeSmuMAR#3]
When running DeSmuMAR.exe for the first time, I choose an aspect ratio and resolution to match my current display settings. This triggers an error that my choices are bigger than the display. However, it specifies at the bottom that it is 0 pixels bigger in either dimension, so it seems like a bug.

> Oh no! The Aspect Ratio and Resolution you chose would result in a DeSmuME window that is bigger than your display.
> To reduce the size, try reduce the resolution or use a smaller aspect ratio
> Since you are trying to use the same aspect ratio for DeSmuME as your Screen, i'm assuming you want to go fullscreen, if this is the case, you should lower the resolution or set the screens amount to "One LCD" in DeSmuME as that will help lower the window size.
> If your curious, you tried to resize DeSmuME to 1920x1080
> That size is: 0 pixels wider & 0 pixels taller than your display :O

**Comment by malexj93** [comment]
For reference, here's the log leading up to it

> Let's go ahead and reset the AspectRatio, Screens, and Resolution value's so you can enter new values.
> Which aspect ratio do you want (e.g. 4:3, 16:9, 21:9, e.t.c):
> \> **16:9**
> Do you want both screens to be shown with DeSmuME? (y/n):
> \> **n**
> Which resolution do you want (e.g. 720, 1080, 1440, e.t.c):
> \> **1080**

**Comment by rlaPHOENiX** [comment]
That is an interesting response, though, its telling you this because it cannot actually show you it at that size as it has to account for the window border and the menu bar at the top fo DeSmuME, I still have yet to find a way to do a proper fullscreen setup.

So technically this isn't a bug. You could try do slightly smaller like 1020p or something.
