### ISSUE TITLE
Program will not Open

### ISSUE THREAD

**Issue by ItsMrNarwhal** [rlaphoenix/DeSmuMAR#7]
Recently downloaded DeSmuMAR and have been trying to get it to work for awhile now, everytime the file is opened it opens a cmd style box for .1 of a second and closes instantly. 

Any help would be appreciated.

**Comment by rlaphoenix** [comment]
What does your DeSmuMAR folder currently look like?

**Comment by ItsMrNarwhal** [comment]
First off thank you for the reply! I appreciate the help.

These are the 3 variations of files I have attempted, all resulting in the same issue https://imgur.com/a/XK8GWHR
I've made sure .NET Core 3.1 is installed as well, tried clean installs of both DeSmuMar and DeSmu
I notice I don't have a DeSmuMAR.ini file though, so maybe this is the issue?

Thanks :D

**Comment by ItsMrNarwhal** [comment]
After fiddling around a good bit more it seemed to be deleting the DeSmuMe.exe after a clean install worked out, thank you again for the help!
